package DB_model;
// Generated 10/09/2018 04:31:19 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TRoutes generated by hbm2java
 */
public class TRoutes  implements java.io.Serializable {


     private Date pkDate;
     private TUserInformation TUserInformation;
     private TVehicle TVehicle;
     private byte[] travel;
     private String details;

    public TRoutes() {
    }

	
    public TRoutes(Date pkDate, TUserInformation TUserInformation, TVehicle TVehicle, byte[] travel) {
        this.pkDate = pkDate;
        this.TUserInformation = TUserInformation;
        this.TVehicle = TVehicle;
        this.travel = travel;
    }
    public TRoutes(Date pkDate, TUserInformation TUserInformation, TVehicle TVehicle, byte[] travel, String details) {
       this.pkDate = pkDate;
       this.TUserInformation = TUserInformation;
       this.TVehicle = TVehicle;
       this.travel = travel;
       this.details = details;
    }
   
    public Date getPkDate() {
        return this.pkDate;
    }
    
    public void setPkDate(Date pkDate) {
        this.pkDate = pkDate;
    }
    public TUserInformation getTUserInformation() {
        return this.TUserInformation;
    }
    
    public void setTUserInformation(TUserInformation TUserInformation) {
        this.TUserInformation = TUserInformation;
    }
    public TVehicle getTVehicle() {
        return this.TVehicle;
    }
    
    public void setTVehicle(TVehicle TVehicle) {
        this.TVehicle = TVehicle;
    }
    public byte[] getTravel() {
        return this.travel;
    }
    
    public void setTravel(byte[] travel) {
        this.travel = travel;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }




}


