package DB_model;
// Generated 10/09/2018 04:31:19 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TUserInformation generated by hbm2java
 */
public class TUserInformation implements java.io.Serializable {

    private String pkId;
    private String name;
    private String surname;
    private String secondSurname;
    private String area;
    private String phoneNumber;
    private String email;
    private String address;
    private String vehicle;

    private Set TIncidentses = new HashSet(0);
    private Set TRouteses = new HashSet(0);
    private Set TFailureses = new HashSet(0);

    public TUserInformation() {
    }

    public TUserInformation(String pkId, String name, String surname, String secondSurname, String area, String phoneNumber, String email, String address, String vehicle) {
        this.pkId = pkId;
        this.name = name;
        this.surname = surname;
        this.secondSurname = secondSurname;
        this.area = area;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.address = address;
        this.vehicle = vehicle;
    }

    public TUserInformation(String pkId, String name, String surname, String secondSurname, String area, String phoneNumber, String email, String address, String vehicle, Set TIncidentses, Set TRouteses, Set TFailureses) {
        this.pkId = pkId;
        this.name = name;
        this.surname = surname;
        this.secondSurname = secondSurname;
        this.area = area;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.address = address;
        this.vehicle = vehicle;
        this.TIncidentses = TIncidentses;
        this.TRouteses = TRouteses;
        this.TFailureses = TFailureses;
    }

    public String getPkId() {
        return this.pkId;
    }

    public void setPkId(String pkId) {
        this.pkId = pkId;
    }

    public String getName() {
        return this.name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getSecondSurname() {
        return secondSurname;
    }

    public void setSecondSurname(String secondSurname) {
        this.secondSurname = secondSurname;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getVehicle() {
        return vehicle;
    }

    public void setVehicle(String vehicle) {
        this.vehicle = vehicle;
    }

    public Set getTIncidentses() {
        return this.TIncidentses;
    }

    public void setTIncidentses(Set TIncidentses) {
        this.TIncidentses = TIncidentses;
    }

    public Set getTRouteses() {
        return this.TRouteses;
    }

    public void setTRouteses(Set TRouteses) {
        this.TRouteses = TRouteses;
    }

    public Set getTFailureses() {
        return this.TFailureses;
    }

    public void setTFailureses(Set TFailureses) {
        this.TFailureses = TFailureses;
    }

    @Override
    public String toString() {
        return "TUserInformation{" + "pkId=" + pkId + ", name=" + name + ", surname=" + surname + ", secondSurname=" + secondSurname + ", area=" + area + ", phoneNumber=" + phoneNumber + ", email=" + email + ", address=" + address + ", vehicle=" + vehicle + '}';
    }

}
