package DB_model;
// Generated 10/09/2018 04:31:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TVehicle generated by hbm2java
 */
public class TVehicle  implements java.io.Serializable {


     private String pkLicensePlate;
     private String model;
     private String brand;
     private String yearPurchase;
     private Set TIncidentses = new HashSet(0);
     private Set TRouteses = new HashSet(0);
     private Set TFailureses = new HashSet(0);

    public TVehicle() {
    }

	
    public TVehicle(String pkLicensePlate, String model, String brand, String yearPurchase) {
        this.pkLicensePlate = pkLicensePlate;
        this.model = model;
        this.brand = brand;
        this.yearPurchase = yearPurchase;
    }
    public TVehicle(String pkLicensePlate, String model, String brand, String yearPurchase, Set TIncidentses, Set TRouteses, Set TFailureses) {
       this.pkLicensePlate = pkLicensePlate;
       this.model = model;
       this.brand = brand;
       this.yearPurchase = yearPurchase;
       this.TIncidentses = TIncidentses;
       this.TRouteses = TRouteses;
       this.TFailureses = TFailureses;
    }
   
    public String getPkLicensePlate() {
        return this.pkLicensePlate;
    }
    
    public void setPkLicensePlate(String pkLicensePlate) {
        this.pkLicensePlate = pkLicensePlate;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getYearPurchase() {
        return this.yearPurchase;
    }
    
    public void setYearPurchase(String yearPurchase) {
        this.yearPurchase = yearPurchase;
    }
    public Set getTIncidentses() {
        return this.TIncidentses;
    }
    
    public void setTIncidentses(Set TIncidentses) {
        this.TIncidentses = TIncidentses;
    }
    public Set getTRouteses() {
        return this.TRouteses;
    }
    
    public void setTRouteses(Set TRouteses) {
        this.TRouteses = TRouteses;
    }
    public Set getTFailureses() {
        return this.TFailureses;
    }
    
    public void setTFailureses(Set TFailureses) {
        this.TFailureses = TFailureses;
    }




}


